version: '3'

services:
  web:
    build: ./docker/webserver
    image: mypie
    ports:
      - "80:8080"
      - "443:443"
    volumes:
      - .:/var/www/mypie
    depends_on:
      - db
    tty: true

  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - ~/.mysql-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=mypie
      - MYSQL_USER=mypie
      - MYSQL_PASSWORD=mypiepassword
